#!bin/bash

make 15_puzzle.from_goal_no_pruning
make 24_puzzle.from_goal_no_pruning
make hanoi4_12.from_goal_no_pruning
make hanoi4_14.from_goal_no_pruning
make hanoi4_17.from_goal_no_pruning
make topspin12_4.from_goal_no_pruning
make topspin14_4.from_goal_no_pruning
make topspin17_4.from_goal_no_pruning
make rubik3.from_goal_no_pruning